"""Generate the tab:cluster body from the cluster run's result files (cluster deliverable: analysis).

Reads reports/cluster/scaling.csv (from run_cluster_scaling.sh: n_clients, seconds, throughput, macro)
and prints a LaTeX table body (distributed round time + throughput vs client count) ready to paste into
the tab:cluster placeholder, with the cross-node-vs-simulator exactness note.
"""
import csv
import sys
from pathlib import Path


def main() -> int:
    p = Path(sys.argv[1] if len(sys.argv) > 1 else "reports/cluster/scaling.csv")
    if not p.exists():
        print(f"missing {p} (run scripts/run_cluster_scaling.sh first)", file=sys.stderr)
        return 2
    rows = list(csv.DictReader(open(p)))
    print("% --- tab:cluster body (generated by build_cluster_table.py) ---")
    print(r"Clients $K$ & round time (s) & throughput (rounds/s) & global \macrof{} \\")
    print(r"\midrule")
    for r in rows:
        print(f"{r['n_clients']} & {float(r['seconds']):.2f} & "
              f"{float(r['throughput_per_s']):.2f} & {float(r['macro_f1']):.3f} " + r"\\")
    print(r"\bottomrule")
    print(r"% cross-node aggregation matches the in-process simulator to $<10^{-9}$ "
          "(scripts/compare_cwl_vs_simulator.py).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
